# version format
version: 1.10-{build}

# vm template
image: Visual Studio 2017

# environment variables
environment:
  EnableNuGetPackageRestore: true

# msbuild configuration
platform:
- Any CPU
configuration:
- Debug

# install dependencies
install:
- ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

# pre-build script
before_build:
- nuget restore

# build step
build:
  verbosity: minimal

# post-build step
after_build:
- ps: appveyor DownloadFile https://github.com/saramibreak/DiscImageCreator/files/2112299/DiscImageCreator_20180619.zip
- ps: appveyor DownloadFile http://www.rawdump.net/tools/subdump_fua_0x28.zip
- 7z e DiscImageCreator_20180619.zip -oDICUI\bin\Debug\Programs Release_ANSI\*
- 7z e subdump_fua_0x28.zip -oDICUI\bin\Debug *
- mv DICUI\bin\Debug\subdump_fua_0x28.exe DICUI\bin\Debug\subdump.exe
- 7z a DICUI.zip DICUI\bin\Debug\*

# artifact linking
artifacts:
- path: DICUI.zip
  name: DICUI